# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2022
#  @credits:    AKAE
#
#  @license:    BSDv3
#  @maintainer: Andreas Kaeberlein
#  @email:      andreas.kaeberlein@web.de
#
#  @file:       doxygen.yml
#  @date:       2022-12-21
#
#  @see:        https://yonatankra.com/2-ways-to-use-your-docker-image-in-github-actions/
#  @see:        https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
#  @brief:      Runs Doxygen and pdf build
#
# ************************************************************************


name: doxygen

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  doxygen:
    runs-on: ubuntu-latest
    container: dolphinics/doxygen:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Prepare Dirs
        run: |
          mkdir -p ./doxygen/out
      - name: Run Doxygen
        run: |
          doxygen --version
          doxygen ./doxygen/Doxyfile
      - name: Run Latex
        run: |
          pdflatex --version
          (cd ./doxygen/out/latex && make)  # build pdf without path change
          mv ./doxygen/out/latex/refman.pdf ./${{ github.event.repository.name }}_ug.pdf    # move to top
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Userguide
          path: ${{ github.event.repository.name }}_ug.pdf
          retention-days: 1
